on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
name: Update gist with latest reads
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Update gist
        run: node index.js
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}